spring.datasource.url= jdbc:postgresql://${db-host}/${db-database}
spring.datasource.username= postgres
spring.datasource.password= loutre

#liquibase
spring.liquibase.url=jdbc:postgresql://${db-host}/${db-database}
spring.liquibase.user=postgres
spring.liquibase.password=loutre
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000

# Hibernate ddl auto (create, create-drop, validate, update) // For production, this property should be validate.
spring.jpa.hibernate.ddl-auto= update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation= true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.application.name=Pinya
server.port=8085
logging.file.name=logs/app.log

# swagger-ui path will be: http://localhost:8080/swagger-ui/index.html
springdoc.swagger-ui.path=/swagger-ui.html

# Login GitHub
spring.security.oauth2.client.registration.github.client-id=Ov23liwuHSOPfLWCfmkX
spring.security.oauth2.client.registration.github.client-secret=d351eceb574e2f53064e71f2d52930ece2b23099

# Login Google
spring.security.oauth2.client.registration.google.client-id=1062594881124-0a51d4sear7oo8tleipp1l08avqqgbeg.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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

#Detailed security logs
#logging.level.org.springframework.security=DEBUG # TRACE(?)
#logging.level.org.springframework.web=DEBUG

#Avatar (files) max size
spring.servlet.multipart.max-file-size=500KB
spring.servlet.multipart.max-request-size=500KB

# --- RabbitMQ --- (conteneur Rancher Desktop)
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin
spring.rabbitmq.virtual-host=/

spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.initial-interval=3s
spring.rabbitmq.listener.simple.retry.max-attempts=5
spring.rabbitmq.listener.simple.retry.multiplier=2
spring.rabbitmq.listener.simple.retry.max-interval=30s
###spring.rabbitmq.listener.simple.auto-startup=false : lancer l'app sans que RabbitMQ(listener) soit lancé

# Queues
app.rabbitmq.exchange=app.exchange
app.rabbitmq.routing-key.email=email.routing.key

# --- Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=valentinbelhomme@gmail.com
spring.mail.password=jfyc nnwt dmeg dcos
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# --- Constantes applicatives ---
pinya.rabbitmq.exchange=email.exchange
pinya.rabbitmq.queue=email.queue
pinya.rabbitmq.queue.email=email.queue
pinya.rabbitmq.dlq=email.queue.dlq
pinya.rabbitmq.routing-key=email.routing

## For tests
#pinya.app.jwtExpirationMs= 600000
#pinya.app.jwtRefreshExpirationMs= 1200000

# APP Properties JWT Credentials de properties a mettre dans un fichier � part qui part pas sur Git (gitignore)
pinya.app.jwtsecret= kTmGrq21vADhhtDJZk8YmLYSSqBWJj4chsVk/yXXWP8d3Rj3y1ib+mJyl+3gYivb/hxgnUgZ4IHuVfP+Rt44CQ==
pinya.app.jwtExpirationMs= 3600000
pinya.app.jwtRefreshExpirationMs= 86400000